repos:
    # blak formatter
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black
    # flake8 linter
    - repo: https://github.com/pycqa/flake8
      rev: 6.1.0
      hooks:
          - id: flake8
            args:
                - '--max-line-length=130'
                - '--exclude'
                - 'requirements.txt'
    # mypy type validator
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.14.1
      hooks:
          - id: mypy
    # pytest test runner
    - repo: local
      hooks:
          - id: pytest-check
            name: pytest-check
            entry: pytest
            language: system
            pass_filenames: false
            always_run: true
    # pre-commit general hooks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
            files: '^(?!requirements\.txt$).*'
          - id: trailing-whitespace
