name: push-pull hooks

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    pre-commit:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout the code
            - name: Checkout repository
              uses: actions/checkout@v3

            # Step 2: Set up Python
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12

            # Step 3: Install dependencies
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            # Step 4: Install pre-commit
            - name: Install pre-commit
              run: |
                  pip install pre-commit

            # Step 5: Run pre-commit hooks
            - name: Run pre-commit hooks
              run: pre-commit run --all-files
